<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.twozo</groupId>
	<artifactId>banking-application-system</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>

	<!-- Java Version -->

	<properties>

		<maven.compiler.source>17</maven.compiler.source>

		<maven.compiler.target>17</maven.compiler.target>

	</properties>

	<!-- Dependencies -->

	<dependencies>

		<!-- PostgresSQL Driver -->

		<dependency>

			<groupId>org.postgresql</groupId>

			<artifactId>postgresql</artifactId>

			<version>42.7.5</version>

		</dependency>

		<!-- https://mvnrepository.com/artifact/com.zaxxer/HikariCP -->

		<dependency>

			<groupId>com.zaxxer</groupId>

			<artifactId>HikariCP</artifactId>

			<version>6.2.1</version>

		</dependency>

		<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->

		<dependency>

			<groupId>org.slf4j</groupId>

			<artifactId>slf4j-api</artifactId>

			<version>2.0.11</version>

		</dependency>

		<!-- https://mvnrepository.com/artifact/ch.qos.logback/logback-classic -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.5.16</version>
			<scope>compile</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-simple -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>2.0.16</version>
			<scope>test</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api -->
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>6.1.0</version>
			<scope>provided</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.18.2</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310 -->
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
			<version>2.18.2</version>
		</dependency>

	</dependencies>

	<!-- Build Configuration -->	

	<build>

		<plugins>

			<!-- Maven WAR Plugin (For Packaging as a WAR file) -->

			<plugin>

				<groupId>org.apache.maven.plugins</groupId>

				<artifactId>maven-war-plugin</artifactId>

				<version>3.4.0</version>

				<configuration>

					<failOnMissingWebXml>false</failOnMissingWebXml>
					<!-- Allows WAR packaging without web.xml -->

				</configuration>

			</plugin>

		</plugins>

	</build>

</project>